### PR TITLE
Minor tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
@april: since I'm on Windows and I'm having trouble running the devserver, please verify these changes look good before merging. :)

### CODE REVIEW

**Comment by april** [comment]
I like most of the fixes, but this creates sections where the top margin (above a table) is different from the bottom margin (below a table).  It's a bit unsightly, which is why I think I had it set to 0 in the first place.  Maybe just try setting the bottom margin to 0?  See here for an example:

screen shot 2017-05-15 at 3 20 22 pm

**Comment by XhmikosR** [comment]
If I set it to 0 then we have the vertical scrollbar on desktop. 1px would
work though. Or even better maybe setting the same as top margin
 I'm afk but I can check later for the exact value .

**Comment by april** [comment]
The top-margin is actually 0 by default.  But 1px won't break the world or anything.  :)

**Comment by XhmikosR** [comment]
@april: can you check now? I also switched from IDs to a class selector.

**Comment by april** [comment]
BTW I did check this and it looks good, just haven't had time to merge it.  I want you to know that I'm not ignoring you, just swamped.  :)

**Comment by XhmikosR** [comment]
No worries, merge when you can :)

**Comment by april** [comment]
Thanks so much!

**Pull request merged**
