### PR TITLE
Instruct search engines not to index the analysis page.

### PR DESCRIPTION
**Pull request by floatingatoll**
Add `<meta name="robots" content="noindex">` to both the static and the dynamic `analyze.html` pages. This required adding a second template block to `base.html` so that we can introduce the noindex header for this page only.

### CODE REVIEW

**Comment by floatingatoll** [comment]
This might already be covered by the robots.txt change April committed for `^/*.html$` or so, which would obsolete my patch here.

**Comment by floatingatoll** [comment]
Nope, it doesn't. If this change is accepted, WFM. Alternately, `Disallow: /analyze*` would probably be sufficient and not require more significant work.

**Comment by caugner** [comment]
> Alternately, Disallow: /analyze* would probably be sufficient and not require more significant work.

Yes, a `robots.txt` solution is probably slightly more elegant.

**Comment by gene1wood** [comment]
Ya, going to go with `robots.txt` in #198. Thank you for this PR though!

**Pull request closed without merging**
