### PR TITLE
Update Bootstrap to v3.3.7.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by marumari** [comment]
This doesn't actually use the bare bootstrap, it uses the Bootswatch Readable configuration.  I'll look into updating it as soon as I have a chance though.  Thanks!

**Comment by XhmikosR** [comment]
I'm aware of that and that's exactly what this updates. ;)

**Comment by marumari** [comment]
Damn, you are awesome.  I'll work on these when I get a moment.  \*tips her hat\*

**Comment by marumari** [comment]
This was done here:

https://github.com/mozilla/http-observatory-website/commit/75feb28d8bb0a91f01eb326c3ea27872fe7420f6

Thanks for submitting this!

**Pull request closed without merging**
