### PR TITLE
changes the href of faq page's What is htbridge.com? section

### PR DESCRIPTION
**Pull request by Harsh3363**
My pull request resolves issue #273 I have changed the link associated with What is htbridge.com?  section in the faq page as asked the domain name as changed I have added the link accordingly.

### CODE REVIEW

**Comment by gene1wood** [comment]
I've  confirmed that these are the same provider ( https://www.instagram.com/htbridge/ )

**Comment by gene1wood** [comment]
@Harsh3363 Thanks for the PR. I expanded on your change to include some additiona htbridge references in #278

**Comment by Harsh3363** [comment]
> @Harsh3363 Thanks for the PR. I expanded on your change to include some additiona htbridge references in #278

Hii @gene1wood can you explain what does this mean like was PR merged or got rejected?

**Comment by gene1wood** [comment]
I created a new PR with your suggestion (#278), with a fixed URL (yours was missing the `/ssl` and additional references to htbridge removed. So this PR, #277 was not merged but your change (with a small fix) is present and merged in #278

**Pull request closed without merging**
